version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    hostname: zookeeper
    ports:
      - "2181:2181"
    container_name: zookeeper

  kafka:
    image: wurstmeister/kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.53.0.20:9092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
    depends_on:
      - zookeeper
    container_name: kafka

#  kafka-manager:
#    image: sheepkiller/kafka-manager
#    links:
#      - kafka
#      - zookeeper
#    environment:
#      ZK_HOSTS: zookeeper:2181
#      APPLICATION_SECRET: "letmein"
#    ports:
#      - "9001:9000"
#    expose:
#      - "9001"

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: "qweasdzxc"
      MYSQL_USER: 'root'
      MYSQL_PASS: 'qweasdzxc'
    image: "mysql:5.7.18"
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - "./db:/var/lib/mysql"
      - "./conf/my.cnf:/etc/my.cnf"
      - "./init:/docker-entrypoint-initdb.d/"

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

